name: flutter_on_december
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  dots_indicator: ^1.0.0
  font_awesome_flutter: ^8.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/1202/image.jpg
    - assets/1202/image1.jpg
    - assets/1202/image2.jpg
    - assets/1204/american_express.jfif
    - assets/1204/american_express_back_side.jpg
    - assets/1204/great_success_animation.gif
    - assets/1206/backgroundImage.jpg
    - assets/1206/image.jpg
    - assets/1206/backgroundImage1.jpg
    - assets/1206/image1.jpeg
    - assets/1206/backgroundImage2.gif
    - assets/1206/image2.jpg
    - assets/1206/backgroundImage3.jpg
    - assets/1206/image3.jpg
    - assets/1206/backgroundImage4.jfif
    - assets/1206/image4.webp

  fonts:
    - family: San Marino Beach
      fonts:
        - asset: fonts/San Marino Beach.otf
    - family: Kitten Bold 400
      fonts:
        - asset: fonts/Kitten Bold 400.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf


